/**
 * Plugin interface strings, Spanish (default, Mexican-neutral) and English.
 * This covers only what the plugin itself shows: commands, menus, settings,
 * modal, pane chrome, and notices. It never touches Codazo's output: the
 * review contract, the prompts, saved notes, and exports are unchanged.
 */
export type UiLanguage = 'es' | 'en';
export const UI_LANGUAGES: readonly UiLanguage[] = ['es', 'en'];

const es = {
  category: { spelling: 'Ortografía / acento', grammar: 'Gramática', verb: 'Verbo / tiempo', alternative: 'Alternativa natural' },
  optionalAlternative: 'Una alternativa opcional',
  // Commands and menu
  cmdReviewSelection: 'Revisar la selección', cmdStudySelection: 'Guía de estudio de la selección', cmdReviewNote: 'Revisar toda la nota', cmdOpenPane: 'Abrir el panel de revisión',
  cmdLoadSaved: 'Cargar la revisión guardada de esta nota', cmdCreateRevision: 'Crear nota de revisión mía', cmdSaveReview: 'Guardar revisión en la bóveda', cmdSaveStudy: 'Guardar hoja de estudio en la bóveda',
  cmdExportJson: 'Exportar la sesión actual (JSON)', cmdExportHtml: 'Exportar la sesión actual (HTML)', cmdCancel: 'Cancelar la revisión en curso',
  menuInterpretation: 'Interpretación', menuTools: 'Herramientas', menuReview: 'Revisar la selección', menuStudy: 'Guía de estudio de la selección',
  // Modal
  modalTitleStudy: 'Guía de estudio de la selección', modalTitleSelection: 'Revisar la selección', modalTitleNote: 'Revisar toda la nota',
  modalStudyIntro: 'Solo palabras por encima de tu nivel y los verbos usados, con sus conjugaciones. Sin observaciones sobre tu escritura.',
  modalTitleExcerpt: 'Extracto de la selección', modalExcerptIntro: 'Para texto que estás leyendo, no que escribiste: significado, palabras y verbos, sin correcciones. Se guarda como nota en Extractos/.', modalExcerptKind: 'Tipo de extracto', modalExcerptKindDesc: 'Detectado por la forma de la selección; cámbialo si hace falta.', excerptWord: 'Palabra', excerptPhrase: 'Frase', excerptParagraph: 'Párrafo', modalConfirmExcerpt: 'Explicar el extracto',
  cmdAddGloss: 'Añadir traducción a la selección', glossTitle: 'Traducción en línea', glossMeaning: 'En inglés', glossDesc: 'Se guarda como {palabra|traducción}. En el editor y en la vista de lectura verás solo la palabra subrayada; al pasar el cursor aparece la traducción.', glossAdd: 'Añadir',
  cmdInsertIntent: 'Insertar intención en inglés', menuInsertIntent: 'Insertar intención en inglés', noticeIntentExists: 'Esta nota ya tiene una intención en inglés.',
  cmdExcerpt: 'Extracto de la selección', menuExcerpt: 'Extracto de la selección', statusExcerpting: 'Preparando tu extracto…', excerptTitle: 'Extracto', meaning: 'Significado', revealHint: 'intenta primero, luego abre', excerptReady: 'Extracto listo',
  modalExactText: 'Este es exactamente el texto que se enviará al proveedor. Nada más de la bóveda sale de aquí: ni el nombre de la nota, ni sus propiedades, ni el resto del contenido.',
  modalTextAria: 'Texto que se enviará',
  modalTooLong: (n: number, max: number) => `El texto tiene ${n} caracteres; el máximo es ${max}. Selecciona un fragmento más corto.`,
  modalChars: (n: number) => `${n} caracteres.`,
  modalIntent: 'Intención en inglés (opcional)', modalIntentDesc: 'Qué querías decir. Si la escribes, también se envía.', modalIntentPlaceholder: 'I wanted to say that…', modalIntentFromNote: 'Tomada del callout «English Intent» de tu nota; puedes editarla. El callout no se envía como parte del texto en español.',
  modalLevel: 'Nivel', modalLevelStudy: 'Tu nivel (se estudian las palabras por encima de él)',
  modalProvider: (label: string) => `Proveedor: ${label}. La IA puede equivocarse; tu texto original no cambia.`,
  modalNoProvider: 'Configura un proveedor y una clave en los ajustes de Codazo antes de revisar.',
  cancel: 'Cancelar', modalConfirmReview: 'Revisar mi texto', modalConfirmStudy: 'Crear guía de estudio',
  // Pane
  paneInFlight: 'Revisando tu texto… Solo hay una revisión en curso a la vez.',
  statusReviewing: 'Revisando tu texto…', statusStudying: 'Preparando tu guía de estudio…', statusDone: (mode: 'review' | 'study' | 'excerpt', seconds: number) => `${mode === 'study' ? 'Guía de estudio lista' : mode === 'excerpt' ? 'Extracto listo' : 'Revisión lista'} en ${seconds} s.`, statusFailed: 'La solicitud falló.', dismiss: 'Cerrar',
  paneEyebrow: 'Spanish Writing Studio · Codazo',
  tabResult: 'Resultado', tabIndex: 'Índice', cmdOpenIndex: 'Abrir el índice de Codazo', indexEmpty: 'Todavía no hay nada guardado en la carpeta de Codazo.', indexThisNote: 'De esta nota', indexNoneForNote: 'Esta nota todavía no tiene contenido de Codazo.', indexNoNote: 'No hay ninguna nota abierta.', indexAll: 'Toda la carpeta de Codazo', indexLoad: 'Cargar en el panel (sin llamar al modelo)', indexOpen: 'Abrir nota', indexProgress: 'progreso', indexHint: (n: number) => `Ver el índice: ${n} ${n === 1 ? 'elemento guardado' : 'elementos guardados'}.`,
  indexKind: { review: 'Revisiones', study: 'Hojas de estudio', excerpt: 'Extractos', revision: 'Mis revisiones', palabra: 'Palabras', verbo: 'Verbos' } as Record<string, string>,
  paneEmpty: 'Selecciona algo que escribiste en español y usa «Codazo: revisar la selección». Tu texto no se envía hasta que lo confirmes.',
  paneNote: (path: string) => `Nota: ${path}`,
  paneStaleAmbiguous: 'El texto revisado aparece más de una vez en la nota; la revisión se conserva pero no se puede ubicar con seguridad.',
  paneStaleMissing: 'El texto revisado ya no está igual en la nota; la revisión se conserva como historial, sin marcas en el editor.',
  paneUnavailable: 'La nota de origen no está abierta. Ábrela para ver las marcas.',
  actionRevision: 'Crear nota de revisión mía', actionSaveReview: 'Guardar revisión', actionSaved: 'Revisión guardada', actionSaveStudy: 'Guardar hoja de estudio', actionExportJson: 'Exportar JSON', actionExportHtml: 'Exportar HTML',
  observations: 'Observaciones', observationsIntro: 'Las sugerencias son información para ti, no cambios automáticos. Las alternativas no son errores.', noObservations: 'Sin observaciones en esta versión.',
  // Render
  yourText: 'Tu texto', studyGuide: 'Guía de estudio', sourceAria: 'Texto original con marcas',
  idleReview: 'Pasa el cursor o elige una palabra marcada para ver la observación.', idleStudy: 'Pasa el cursor o elige una palabra marcada para ver su significado.', idleStudyEmpty: 'No hay palabras por encima de tu nivel en esta selección.',
  suggestion: 'Sugerencia:', suggestionOptional: 'Sugerencia opcional:', wordToStudy: 'Palabra para estudiar', verbToStudy: 'Verbo para estudiar', legendWords: 'Palabras', legendVerbs: 'Verbos',
  seeInNote: 'Ver en la nota', goTo: (quote: string) => `Ir a «${quote}» en la nota`, morePractice: 'Un poco más de práctica', notice: 'Observa', hint: 'Pista', tryAgain: 'Inténtalo otra vez', newWords: 'Palabras nuevas en esta sugerencia',
  summary: 'Resumen',
  summaryLine: (c: number, a: number, w: number, v: number) => `${c} ${c === 1 ? 'corrección' : 'correcciones'}, ${a} ${a === 1 ? 'alternativa opcional' : 'alternativas opcionales'}, ${w} palabras y ${v} verbos para estudiar.`,
  intentLabel: (assessment: string) => `Intención (${assessment}):`, strengths: 'Lo que ya funciona', nextSteps: 'Próximos pasos',
  wordsToStudy: 'Palabras para estudiar', noNewWords: 'No hay palabras nuevas en esta versión.', badgeNew: 'Nueva', badgePractice: 'Practicar', originalAndExamples: 'Texto original y ejemplos', fromYourText: (quote: string) => `De tu texto: «${quote}»`,
  verbsToStudy: 'Verbos para estudiar', noVerbs: 'Las referencias de verbos aparecen cuando la revisión las incluye.', referenceUnavailable: (reason: string) => `Referencia no disponible: ${reason}`,
  sourceLine: (label: string, license: string) => `Fuente: ${label} · Licencia: ${license}`,
  // Notices
  noticeOpenSource: 'Abre la nota de origen para ir a la frase.',
  noticeDisclosure: 'Codazo guardará esta nota como Markdown normal dentro de tu bóveda. Es texto sin cifrar y se sincroniza como el resto de tus notas.',
  noticeCreated: (path: string) => `Codazo creó ${path}.`, noticeAlreadySaved: (path: string) => `Esta revisión ya está guardada en ${path}.`, noticeExported: (path: string) => `Codazo exportó ${path}.`,
  noticeSavedInvalid: 'La revisión guardada no pasó la validación de Codazo y no se mostrará como retroalimentación confiable.',
  noticeNoPayload: 'Esta nota se guardó antes de que Codazo incluyera los datos para recargarla; se abre como nota. Las nuevas sí se recargan en el panel.',
  savedReviewLabel: 'Revisión guardada', unknown: 'desconocido',
  errorGeneric: 'Codazo no pudo completar la acción.', errorWithReason: (reason: string) => `Codazo no pudo completar la acción: ${reason}`,
  errors: {
    SETTINGS_REQUIRED: 'Elige un perfil de proveedor activo en los ajustes de Codazo antes de revisar.',
    INVALID_BASE_URL: 'La URL base no es válida. Usa la raíz del API, por ejemplo https://openrouter.ai/api/v1.',
    HTTPS_REQUIRED: 'Solo se permite http para servidores locales o de tu red privada; para todo lo demás usa https.',
    INVALID_PROFILE: 'El perfil está incompleto: revisa nombre, modelo, tokens y tiempo de espera.',
    INVALID_KEY: 'La clave contiene caracteres no válidos.', UNKNOWN_PROFILE: 'Ese perfil ya no existe.', PROFILE_CHANGED: 'El perfil cambió después de confirmar. No se envió nada; vuelve a abrir la revisión.', KEY_REQUIRED: 'Se necesita una clave para este proveedor.',
    SECURE_STORAGE_UNAVAILABLE: 'El almacenamiento seguro de Obsidian no está cifrando en este equipo (falta el llavero del sistema). La clave solo puede guardarse para esta sesión; Codazo no la guarda en texto plano.',
    TRANSPORT_UNAVAILABLE: 'Esta versión de Codazo funciona solo en Obsidian de escritorio.',
    SETTINGS_UNAVAILABLE: 'La configuración guardada no se pudo leer. Vuelve a introducirla.',
    INVALID_REQUEST: 'El texto seleccionado no cumple los límites de una revisión (hasta 4000 caracteres).',
    IN_FLIGHT: 'Ya hay una revisión en curso. Espera a que termine o cancélala.', CANCELLED: 'Revisión cancelada. Si la solicitud ya salió, el proveedor pudo recibirla.',
    PROVIDER_REFUSED: 'El proveedor no completó la revisión. No se muestra ninguna respuesta parcial.',
    INVALID_OUTPUT: 'La respuesta del proveedor no cumple el contrato de Codazo y se descartó.',
    UPSTREAM_ERROR: 'El proveedor no respondió correctamente. Nada se reintenta automáticamente.',
    TIMEOUT: 'El proveedor tardó más que el tiempo de espera del perfil. Puedes subirlo en los ajustes; nada se reintenta automáticamente.',
    ALREADY_PROCESSED: 'Esta solicitud ya se procesó.', WINDOW_REQUEST_LIMIT: 'Se alcanzó el límite de revisiones para esta sesión de Obsidian.',
    INVALID_FOLDER: 'La carpeta de Codazo no es válida. Usa una ruta dentro de la bóveda.', NO_AVAILABLE_PATH: 'No se encontró un nombre de archivo libre.',
    STALE: 'El texto de la nota cambió; la revisión se conserva pero ya no se puede ubicar en el editor.',
  } as Record<string, string>,
  // Settings
  sProvider: 'Proveedor', sActiveProfile: 'Perfil activo', sActiveProfileDesc: 'Las revisiones usan este perfil. Los perfiles guardan destino, modelo y preferencias; la clave vive en el almacenamiento seguro de Obsidian o solo en memoria.',
  sNone: '— ninguno —', sCreateOne: '— crea un perfil —', sKeyOnDevice: 'clave en este dispositivo', sKeySession: 'clave solo esta sesión', sNoKeyNow: 'sin clave ahora',
  sEdit: 'Editar', sDelete: 'Eliminar', sForgot: (name: string) => `Codazo olvidó el perfil ${name} y su clave.`, sNewProfile: 'Nuevo perfil', sEditProfile: (name: string) => `Editar ${name}`,
  sName: 'Nombre', sNamePlaceholder: 'OpenRouter, Ollama local…', sService: 'Servicio', sServiceDesc: 'OpenAI y Ollama Cloud usan sus destinos fijos. Personalizado acepta cualquier API compatible con OpenAI (OpenRouter, un servidor local).', sCustom: 'Personalizado',
  sBaseUrl: 'URL base', sBaseUrlDesc: 'La raíz del API, sin /chat/completions. Ejemplos: https://openrouter.ai/api/v1, http://localhost:11434/v1. Las solicitudes no siguen redirecciones: un servidor que redirige falla antes de enviar la clave o el texto. http se permite solo hacia localhost, nombres .local o tu red privada, y en ese tramo la clave viaja sin cifrar; para un servidor local sin clave usa un valor como "local".',
  noticeTransportUnavailable: 'Codazo necesita Obsidian de escritorio para enviar solicitudes; en este entorno no se enviará nada.',
  noticeCleartextKey: 'Este perfil usa http: la clave y el texto viajan sin cifrar dentro de tu red. Úsalo solo con un servidor local de confianza y, de preferencia, con una clave que no sea de un servicio en la nube.',
  sModel: 'Modelo', sModelDesc: 'Identificador exacto del modelo tal como lo espera el servicio.', sKey: 'Clave',
  sKeyDescExisting: 'Hay una clave guardada para este perfil. Escribe una nueva solo si quieres reemplazarla. Un servidor local sin clave acepta cualquier valor, por ejemplo "local".',
  sKeyDescNew: 'Se envía únicamente al destino de este perfil, nunca a Codazo; las redirecciones no se siguen. Un servidor local sin clave acepta cualquier valor, por ejemplo "local".',
  sKeyStorage: 'Guardar la clave', sKeyStorageDesc: 'Persistente: en el almacenamiento seguro de Obsidian, cifrado por el sistema; Codazo comprueba que el cifrado esté activo antes de guardar. Sesión: solo en memoria hasta cerrar Obsidian.', sKeyStorageNoSecure: 'El almacenamiento seguro de Obsidian no está cifrando en este equipo, así que Codazo no ofrece guardar la clave: solo se conserva para esta sesión.',
  sSessionOnly: 'Solo esta sesión', sOnDevice: 'En este dispositivo (Secret Storage)', sTokenField: 'Campo de límite de tokens',
  sResponseFormat: 'Formato de respuesta', sResponseFormatDesc: 'OpenAI y Ollama Cloud aceptan json_object. Servidores locales como LM Studio suelen rechazarlo: usa json_schema (probado con LM Studio). Los modelos con razonamiento largo suelen agotar el tiempo de espera.', sPromptOnly: 'Solo instrucciones',
  sTimeout: 'Tiempo máximo de espera (segundos)', sTimeoutDesc: (min: number, max: number, dflt: number) => `Entre ${min} y ${max}. Los modelos locales pueden tardar más de los ${dflt} s predeterminados.`,
  sMaxTokens: 'Máximo de tokens de salida', sMaxTokensDesc: 'Entre 256 y 8192.', sSaveProfile: 'Guardar perfil', sProfileSaved: (label: string) => `Perfil guardado: ${label}.`,
  sVault: 'Bóveda', sFolder: 'Carpeta de Codazo', sFolderDesc: 'Las revisiones, revisiones tuyas y hojas de estudio guardadas se crean dentro de esta carpeta como notas Markdown normales. Son texto sin cifrar y se sincronizan como el resto de tu bóveda.',
  sAutoSave: 'Guardar revisiones automáticamente', sAutoSaveDesc: 'Cada revisión validada se guarda de inmediato como nota en la subcarpeta Reviews, enlazada a tu nota con la propiedad codazo-source. Al volver a una nota, Codazo carga su revisión más reciente desde esa carpeta. Las notas de revisión tuya se crean solo cuando las pides.',
  sAutoStudyNotes: 'Crear notas de palabras y verbos automáticamente', sAutoStudyNotesDesc: 'Tras cada revisión o guía de estudio, Codazo crea una nota por palabra en Palabras/ y una por verbo y tiempo en Verbos/ (por ejemplo «dar · Presente de indicativo»), cada una con la propiedad codazo-progreso para marcar tu avance. Las notas que ya existen no se tocan.',
  actionStudyNotes: 'Guardar palabras y verbos', noticeStudyNotes: (created: number, existing: number) => `Codazo creó ${created} ${created === 1 ? 'nota' : 'notas'} de palabras y verbos${existing ? `; ${existing} ya ${existing === 1 ? 'existía' : 'existían'}` : ''}.`,
  sPrivacy: 'Privacidad', sPrivacyDesc: 'Codazo envía únicamente el texto que ves en la ventana de confirmación, más la intención opcional, al destino del perfil confirmado. Nunca envía el nombre ni la ruta de la nota, ni otras notas; al revisar la nota completa, las propiedades (frontmatter) se quitan antes. Los enlaces o etiquetas dentro del texto que seleccionas viajan tal como están escritos. No hay telemetría, ni cuenta, ni sincronización propia.',
  sSectionsOpen: 'Secciones del panel abiertas', sSectionsOpenDesc: 'Resumen, observaciones, palabras y verbos son secciones plegables. Activado: empiezan abiertas. Desactivado: empiezan cerradas y abres solo lo que quieres ver.',
  sInterface: 'Interfaz', sLanguage: 'Idioma de la interfaz / Interface language', sLanguageDesc: 'Solo cambia los textos del plugin: comandos, menú, ajustes, ventana y panel. La retroalimentación de Codazo, los prompts y las notas guardadas no cambian. / Changes only the plugin\'s own text; Codazo\'s feedback, prompts, and saved notes are unchanged.',
};

const en: typeof es = {
  category: { spelling: 'Spelling / accent', grammar: 'Grammar', verb: 'Verb / tense', alternative: 'Natural alternative' },
  optionalAlternative: 'An optional alternative',
  cmdReviewSelection: 'Review selection', cmdStudySelection: 'Study guide from selection', cmdReviewNote: 'Review current note', cmdOpenPane: 'Open review pane',
  cmdLoadSaved: 'Load saved review from current note', cmdCreateRevision: 'Create linked revision note', cmdSaveReview: 'Save review to vault', cmdSaveStudy: 'Save study sheet to vault',
  cmdExportJson: 'Export current session (JSON)', cmdExportHtml: 'Export current session (HTML)', cmdCancel: 'Cancel review in progress',
  menuInterpretation: 'Interpretation', menuTools: 'Tools', menuReview: 'Review selection', menuStudy: 'Study guide from selection',
  modalTitleStudy: 'Study guide from selection', modalTitleSelection: 'Review selection', modalTitleNote: 'Review the whole note',
  modalStudyIntro: 'Only words above your level and the verbs you used, with their conjugations. No observations about your writing.',
  modalTitleExcerpt: 'Excerpt from selection', modalExcerptIntro: 'For text you are reading, not text you wrote: meaning, words, and verbs, no corrections. Saved as a note in Extractos/.', modalExcerptKind: 'Excerpt kind', modalExcerptKindDesc: 'Detected from the shape of the selection; change it if needed.', excerptWord: 'Word', excerptPhrase: 'Phrase', excerptParagraph: 'Paragraph', modalConfirmExcerpt: 'Explain the excerpt',
  cmdAddGloss: 'Add translation to selection', glossTitle: 'Inline translation', glossMeaning: 'In English', glossDesc: 'Saved as {word|translation}. In the editor and reading view you see only the underlined word; hovering shows the translation.', glossAdd: 'Add',
  cmdInsertIntent: 'Insert English intent', menuInsertIntent: 'Insert English intent', noticeIntentExists: 'This note already has an English intent.',
  cmdExcerpt: 'Excerpt from selection', menuExcerpt: 'Excerpt from selection', statusExcerpting: 'Preparing your excerpt…', excerptTitle: 'Excerpt', meaning: 'Meaning', revealHint: 'try first, then open', excerptReady: 'Excerpt ready',
  modalExactText: 'This is exactly the text that will be sent to the provider. Nothing else leaves the vault: not the note name, its properties, or the rest of its content.',
  modalTextAria: 'Text to be sent',
  modalTooLong: (n, max) => `The text has ${n} characters; the maximum is ${max}. Select a shorter passage.`,
  modalChars: n => `${n} characters.`,
  modalIntent: 'English intent (optional)', modalIntentDesc: 'What you meant to say. If you write it, it is sent too.', modalIntentPlaceholder: 'I wanted to say that…', modalIntentFromNote: 'Taken from the "English Intent" callout in your note; you can edit it. The callout is not sent as part of the Spanish text.',
  modalLevel: 'Level', modalLevelStudy: 'Your level (words above it are studied)',
  modalProvider: label => `Provider: ${label}. AI may be wrong; your original text does not change.`,
  modalNoProvider: 'Set up a provider and a key in Codazo settings before reviewing.',
  cancel: 'Cancel', modalConfirmReview: 'Review my text', modalConfirmStudy: 'Create study guide',
  paneInFlight: 'Reviewing your text… Only one review runs at a time.',
  statusReviewing: 'Reviewing your text…', statusStudying: 'Preparing your study guide…', statusDone: (mode, seconds) => `${mode === 'study' ? 'Study guide ready' : mode === 'excerpt' ? 'Excerpt ready' : 'Review ready'} in ${seconds} s.`, statusFailed: 'The request failed.', dismiss: 'Dismiss',
  paneEyebrow: 'Spanish Writing Studio · Codazo',
  tabResult: 'Result', tabIndex: 'Index', cmdOpenIndex: 'Open the Codazo index', indexEmpty: 'Nothing saved in the Codazo folder yet.', indexThisNote: 'From this note', indexNoneForNote: 'This note has no Codazo content yet.', indexNoNote: 'No note is open.', indexAll: 'All Codazo content', indexLoad: 'Load into the pane (no model call)', indexOpen: 'Open note', indexProgress: 'progress', indexHint: n => `See the index: ${n} saved ${n === 1 ? 'item' : 'items'}.`,
  indexKind: { review: 'Reviews', study: 'Study sheets', excerpt: 'Excerpts', revision: 'My revisions', palabra: 'Words', verbo: 'Verbs' },
  paneEmpty: 'Select something you wrote in Spanish and use "Codazo: Review selection". Your text is not sent until you confirm.',
  paneNote: path => `Note: ${path}`,
  paneStaleAmbiguous: 'The reviewed text appears more than once in the note; the review is kept but cannot be located safely.',
  paneStaleMissing: 'The reviewed text is no longer the same in the note; the review is kept as history, without editor marks.',
  paneUnavailable: 'The source note is not open. Open it to see the marks.',
  actionRevision: 'Create my revision note', actionSaveReview: 'Save review', actionSaved: 'Review saved', actionSaveStudy: 'Save study sheet', actionExportJson: 'Export JSON', actionExportHtml: 'Export HTML',
  observations: 'Observations', observationsIntro: 'Suggestions are information for you, not automatic changes. Alternatives are not errors.', noObservations: 'No observations in this version.',
  yourText: 'Your text', studyGuide: 'Study guide', sourceAria: 'Original text with marks',
  idleReview: 'Hover or choose a marked word to see the observation.', idleStudy: 'Hover or choose a marked word to see its meaning.', idleStudyEmpty: 'No words above your level in this selection.',
  suggestion: 'Suggestion:', suggestionOptional: 'Optional suggestion:', wordToStudy: 'Word to study', verbToStudy: 'Verb to study', legendWords: 'Words', legendVerbs: 'Verbs',
  seeInNote: 'Show in note', goTo: quote => `Go to "${quote}" in the note`, morePractice: 'A little more practice', notice: 'Notice', hint: 'Hint', tryAgain: 'Try again', newWords: 'New words in this suggestion',
  summary: 'Summary',
  summaryLine: (c, a, w, v) => `${c} ${c === 1 ? 'correction' : 'corrections'}, ${a} optional ${a === 1 ? 'alternative' : 'alternatives'}, ${w} words and ${v} verbs to study.`,
  intentLabel: assessment => `Intent (${assessment}):`, strengths: 'What already works', nextSteps: 'Next steps',
  wordsToStudy: 'Words to study', noNewWords: 'No new words in this version.', badgeNew: 'New', badgePractice: 'Practice', originalAndExamples: 'Original text and examples', fromYourText: quote => `From your text: "${quote}"`,
  verbsToStudy: 'Verbs to study', noVerbs: 'Verb references appear when the review includes them.', referenceUnavailable: reason => `Reference unavailable: ${reason}`,
  sourceLine: (label, license) => `Source: ${label} · License: ${license}`,
  noticeOpenSource: 'Open the source note to go to the phrase.',
  noticeDisclosure: 'Codazo will save this note as ordinary Markdown inside your vault. It is unencrypted text and syncs like the rest of your notes.',
  noticeCreated: path => `Codazo created ${path}.`, noticeAlreadySaved: path => `This review is already saved at ${path}.`, noticeExported: path => `Codazo exported ${path}.`,
  noticeSavedInvalid: 'The saved review did not pass Codazo validation and will not be shown as trusted feedback.',
  noticeNoPayload: 'This note was saved before Codazo included the data needed to reload it, so it opens as a note. New ones reload into the pane.',
  savedReviewLabel: 'Saved review', unknown: 'unknown',
  errorGeneric: 'Codazo could not complete the action.', errorWithReason: reason => `Codazo could not complete the action: ${reason}`,
  errors: {
    SETTINGS_REQUIRED: 'Choose an active provider profile in Codazo settings before reviewing.',
    INVALID_BASE_URL: 'The base URL is not valid. Use the API root, for example https://openrouter.ai/api/v1.',
    HTTPS_REQUIRED: 'Plain http is allowed only for local or private-network servers; use https for everything else.',
    INVALID_PROFILE: 'The profile is incomplete: check name, model, tokens, and timeout.',
    INVALID_KEY: 'The key contains invalid characters.', UNKNOWN_PROFILE: 'That profile no longer exists.', PROFILE_CHANGED: 'The profile changed after you confirmed. Nothing was sent; open the review again.', KEY_REQUIRED: 'A key is required for this provider.',
    SECURE_STORAGE_UNAVAILABLE: 'Obsidian\'s secure storage is not encrypting on this computer (no system keychain available). The key can only be kept for this session; Codazo will not store it in plain text.',
    TRANSPORT_UNAVAILABLE: 'This version of Codazo works only in Obsidian for desktop.',
    SETTINGS_UNAVAILABLE: 'The saved configuration could not be read. Enter it again.',
    INVALID_REQUEST: 'The selected text exceeds the limits of a review (up to 4000 characters).',
    IN_FLIGHT: 'A review is already in progress. Wait for it to finish or cancel it.', CANCELLED: 'Review cancelled. If the request already left, the provider may have received it.',
    PROVIDER_REFUSED: 'The provider did not complete the review. No partial answer is shown.',
    INVALID_OUTPUT: 'The provider\'s answer does not meet the Codazo contract and was discarded.',
    UPSTREAM_ERROR: 'The provider did not respond correctly. Nothing is retried automatically.',
    TIMEOUT: 'The provider took longer than the profile\'s timeout. You can raise it in settings; nothing is retried automatically.',
    ALREADY_PROCESSED: 'This request was already processed.', WINDOW_REQUEST_LIMIT: 'The review limit for this Obsidian session was reached.',
    INVALID_FOLDER: 'The Codazo folder is not valid. Use a path inside the vault.', NO_AVAILABLE_PATH: 'No free file name was found.',
    STALE: 'The note text changed; the review is kept but can no longer be located in the editor.',
  },
  sProvider: 'Provider', sActiveProfile: 'Active profile', sActiveProfileDesc: 'Reviews use this profile. Profiles store destination, model, and preferences; the key lives in Obsidian\'s secure storage or in memory only.',
  sNone: '— none —', sCreateOne: '— create a profile —', sKeyOnDevice: 'key on this device', sKeySession: 'key for this session only', sNoKeyNow: 'no key right now',
  sEdit: 'Edit', sDelete: 'Delete', sForgot: name => `Codazo forgot the profile ${name} and its key.`, sNewProfile: 'New profile', sEditProfile: name => `Edit ${name}`,
  sName: 'Name', sNamePlaceholder: 'OpenRouter, local Ollama…', sService: 'Service', sServiceDesc: 'OpenAI and Ollama Cloud use fixed destinations. Custom accepts any OpenAI-compatible API (OpenRouter, a local server).', sCustom: 'Custom',
  sBaseUrl: 'Base URL', sBaseUrlDesc: 'The API root, without /chat/completions. Examples: https://openrouter.ai/api/v1, http://localhost:11434/v1. Requests never follow redirects: a redirecting server fails before the key or text is sent. http is allowed only to localhost, .local names, or your private network, and on that hop the key travels unencrypted; for a keyless local server use a value such as "local".',
  noticeTransportUnavailable: 'Codazo needs Obsidian for desktop to send requests; nothing will be sent in this environment.',
  noticeCleartextKey: 'This profile uses http: the key and the text travel unencrypted inside your network. Use it only with a trusted local server and, preferably, with a key that is not from a cloud service.',
  sModel: 'Model', sModelDesc: 'Exact model identifier as the service expects it.', sKey: 'Key',
  sKeyDescExisting: 'A key is saved for this profile. Enter a new one only to replace it. A local server without a key accepts any value, for example "local".',
  sKeyDescNew: 'Sent only to this profile\'s destination, never to Codazo; redirects are not followed. A local server without a key accepts any value, for example "local".',
  sKeyStorage: 'Key storage', sKeyStorageDesc: 'Persistent: in Obsidian\'s secure storage, encrypted by the operating system; Codazo checks that encryption is active before saving. Session: in memory until Obsidian closes.', sKeyStorageNoSecure: 'Obsidian\'s secure storage is not encrypting on this computer, so Codazo does not offer to store the key: it is kept for this session only.',
  sSessionOnly: 'This session only', sOnDevice: 'On this device (Secret Storage)', sTokenField: 'Token limit field',
  sResponseFormat: 'Response format', sResponseFormatDesc: 'OpenAI and Ollama Cloud accept json_object. Local servers such as LM Studio usually reject it: use json_schema (tested with LM Studio). Long-reasoning models tend to exhaust the timeout.', sPromptOnly: 'Instructions only',
  sTimeout: 'Timeout (seconds)', sTimeoutDesc: (min, max, dflt) => `Between ${min} and ${max}. Local models may need more than the default ${dflt} s.`,
  sMaxTokens: 'Maximum output tokens', sMaxTokensDesc: 'Between 256 and 8192.', sSaveProfile: 'Save profile', sProfileSaved: label => `Profile saved: ${label}.`,
  sVault: 'Vault', sFolder: 'Codazo folder', sFolderDesc: 'Saved reviews, your revisions, and study sheets are created inside this folder as ordinary Markdown notes. They are unencrypted text and sync like the rest of your vault.',
  sAutoSave: 'Save reviews automatically', sAutoSaveDesc: 'Every validated review is saved at once as a note in the Reviews subfolder, linked to your note through the codazo-source property. When you return to a note, Codazo loads its newest review from that folder. Revision notes are created only when you ask.',
  sAutoStudyNotes: 'Create word and verb notes automatically', sAutoStudyNotesDesc: 'After every review or study guide, Codazo creates one note per word in Palabras/ and one per verb and tense in Verbos/ (for example "dar · Presente de indicativo"), each with a codazo-progreso property for tracking your progress. Existing notes are never touched.',
  actionStudyNotes: 'Save words and verbs', noticeStudyNotes: (created, existing) => `Codazo created ${created} word and verb ${created === 1 ? 'note' : 'notes'}${existing ? `; ${existing} already existed` : ''}.`,
  sPrivacy: 'Privacy', sPrivacyDesc: 'Codazo sends only the text shown in the confirmation window, plus the optional intent, to the confirmed profile\'s destination. It never sends the note name or path, or other notes; in whole-note mode the properties (frontmatter) are removed first. Links or tags inside the text you select travel as written. No telemetry, no account, no sync of its own.',
  sSectionsOpen: 'Pane sections start open', sSectionsOpenDesc: 'Summary, observations, words, and verbs are collapsible sections. On: they start open. Off: they start closed and you open only what you want to see.',
  sInterface: 'Interface', sLanguage: 'Interface language / Idioma de la interfaz', sLanguageDesc: 'Changes only the plugin\'s own text: commands, menu, settings, window, and pane. Codazo\'s feedback, prompts, and saved notes are unchanged. / Solo cambia los textos del plugin; la retroalimentación, los prompts y las notas guardadas no cambian.',
};

let current: UiLanguage = 'es';
export function setUiLanguage(language: UiLanguage): void { current = language; }
export function uiLanguage(): UiLanguage { return current; }
/** Current-language strings. Call at render time, not at module load. */
export function t(): typeof es { return current === 'en' ? en : es; }
